import { StyleSheet } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';

export const styles = StyleSheet.create({
 container: {
    flex: 1,
    backgroundColor: '#efefef',
  },
  cardContainer: {
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 20,
    marginBottom: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    width: '90%',
    alignSelf: 'center',
    height: 400,
  },
  firstLetter: {
    fontSize: 48,
    fontWeight: 'bold',
    marginBottom: 10,
    backgroundColor: '#fff',
    width: 80,
    height: 80,
    textAlign: 'center',
    lineHeight: 80,
    borderRadius: 40,
    borderWidth: 3,
    borderColor: '#90bafe',
  },
  textoTopo: {
    fontSize: 26,
    fontWeight: 'bold',
    marginTop: 10,
    paddingLeft: 20,
  },
  nome: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 5,
  },
  cargo: {
    fontSize: 16,
    color: '#ffffff',
    marginBottom: 5,
  },
  empresa: {
    fontSize: 14,
    color: '#ffffffa9',
    marginBottom: 5,
  },
  experiencia: {
    fontSize: 14,
    color: '#ffffff8f',
  },
  level: {
    marginTop: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    color: '#fff',
    fontWeight: 'bold',
    marginBottom: 10,
  },
  tecnologiaText: {
    fontSize: 14,
    color: '#ffffffe7',
  },
  tecnologiaPrincipal: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 15,
  },
  botaoEditar: {
    backgroundColor: 'white',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    width: '90%',
    height: 50,
    borderWidth: 2,
    borderColor: '#3b82f6',
  },
  botaoFinalizar: {
    backgroundColor: '#3b82f6',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    width: '90%',
    height: 50,
    marginTop: 10,
  },
  textoBotao: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
});
